
dependencies:
  build:
    - python:3.6.3

build_targets:
  - name: default
    commands:
        - sudo apt-get update -qq
        - python -m ensurepip --default-pip
        - pip install flake8
        - flake8
    environment:
      - TEST="flake8"
  - name: debian9basicpy2
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
      - OS=debian9
      - PY=2
      - TEST=basic
